sudo: true
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
  - unset _JAVA_OPTIONS
env:
  global:
    - MAVEN_OPTS=-Xmx512m
script:
  - mvn -f src/pom.xml -B -U -T3 -fae -Prelease clean install $ARGS && mvn -f src/community/pom.xml -B -U -T4 -fae -DskipTests -Prelease -PcommunityRelease clean install $COMMUNITY_ARGS
  - grep -H "<testsuite" `find . -iname "TEST-*.xml"` | sed 's/.\/\(.*\)\/target.*:<testsuite .* name="\(.*\)" time="\([^"]*\)" .*/\3\t\2\t\1/' | sort -nr | head -50
before-caching:
  - rm -rf $HOME/.m2/repository/org/geotools
  - rm -rf $HOME/.m2/repository/org/geowebcache
  - rm -rf $HOME/.m2/repository/org/geoserver
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - jdk: oraclejdk8
      env: ARGS="-Dfmt.skip=true" COMMUNITY_ARGS=$ARGS
    - jdk: openjdk11
      env: ARGS="-Dfmt.skip=true" COMMUNITY_ARGS=$ARGS
    - jdk: openjdk11
      env: ARGS="-Dfmt.action=check -Ppmd -Perrorprone -DskipTests=true" COMMUNITY_ARGS="-Dfmt.action=check -DskipTests=true"

